### ISSUE TITLE
Bug with the saved bar and line chart

### ISSUE THREAD

**Issue by pokkeko** [statisticssweden/PxWeb#69] opened 2020-12-08 13:34 UTC
**Describe the bug**
When the bar and line chart is saved as a graph format (png, gif, jpg), there are only bars in the graph, no lines.

**To Reproduce**
1. Go to for example 'https://www.statistikdatabasen.scb.se/pxweb/en/ssd/START__BE__BE0101__BE0101B/BefolkMedianAlder/'
2. Select in 'observations': 'Average age' and 'Median age', in 'sex': 'total' and in 'year' what ever you want, for example 2014-2019.
3. Continue to the table.
4. Choose Chart - Bar and line
5. Save your retrieval for example: 'Fixed starting time' and Save the result as: 'Chart as PNG (png)'.
6. Push Finish and you get the link to PNG-chart (in my case: 'https://www.statistikdatabasen.scb.se/sq/98269').
7. The link reproduce a normal Bar chart with two variables, not a Bar and line chart.

**Expected behavior**
Bar and line chart in PNG format

**Actual behavior**
Bar chart in PNG format

**Links**
Link to the chart 'Same as shown on screen':
https://www.statistikdatabasen.scb.se/sq/98273
Link to the chart 'Chart as PNG (png)':
https://www.statistikdatabasen.scb.se/sq/98274

**Environment information**
 - OS: Win 10 Pro
 - Browser: chrome, firefox, edge, opera, vivaldi etc.
 - Device: PC

**Additional context**
The same bug can be found in all versions of PxWeb from different organizations, for example: 
Statistics Finland (http://pxnet2.stat.fi/PXWeb/pxweb/en/StatFin/) and 
Natural Resources Institute Finland (https://statdb.luke.fi/PXWeb/pxweb/en/LUKE/).

**Comment by likp** [comment] 2020-12-08 14:19
@pokkeko looks like a bug. Nice catch I see if I can find the cause of the problem.

**Comment by likp** [comment] 2020-12-10 12:28
The function ConvertToChartType is missing a conversion for CHART_COLUMNLINE

**Comment by pokkeko** [comment] 2020-12-10 12:49
Ok, thanks!

You can fix it?

el pokke?


Pekka Korhonen
Erityisasiantuntija
Luonnonvarakeskus (Luke)
Tilastopalvelut
PL 2 (Latokartanonkaari 9), 00791 HKI
Puh. 029 532 7339
pekka.korho<mailto:pekka.korhonen@luke.fi><mailto:pekka.korhonen@luke.fi>nen@luke.fi<mailto:pekka.korhonen@luke.fi>
www.luke.fi<http://www.luke.fi>


________________________________
Lähettäjä: likp <notifications@github.com>
Lähetetty: 10. joulukuuta 2020 14:28
Vastaanottaja: statisticssweden/PxWeb
Kopio: Korhonen Pekka (Luke); Mention
Aihe: Re: [statisticssweden/PxWeb] Bug with the saved bar and line chart (#69)


The function ConvertToChartType is missing a conversion for CHART_COLUMNLINE

-

**Comment by petroslikidis** [comment] 2020-12-10 19:06
I just added a fix for it. Hopefully it will be merged in before the next release.

**Comment by likp** [comment] 2021-01-25 14:13
Was fixed in PxWeb 2020v2

**Closed by likp** 2021-01-25 14:13 UTC
Labels: bug
